# Generated by Django 3.2 on 2021-04-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='obtainedu_unit',
            field=models.IntegerField(null=True, verbose_name='取得単位'),
        ),
    ]
